a.out:Employee.o main.o
	g++ -g $^ -o a.out
Employee.o:Employee.cpp
	g++ -g -c Employee.cpp
main.o:main.cpp
	g++ -g -c main.cpp
clean:
	rm *.o a.out
distclean:
	rm *.o a.out count.txt id.txt 1000*





