######################################################################
# Automatically generated by qmake (3.0) Wed Jul 31 11:31:29 2019
######################################################################

QT += widgets

TEMPLATE = app
TARGET = Hello
INCLUDEPATH += .

# Input
SOURCES += main.cpp
