######################################################################
# Automatically generated by qmake (3.0) Wed Jul 31 15:20:18 2019
######################################################################
QT += widgets
TEMPLATE = app
TARGET = Codec
INCLUDEPATH += .

# Input
SOURCES += main.cpp
