######################################################################
# Automatically generated by qmake (3.0) Thu Aug 1 11:11:10 2019
######################################################################
QT += widgets
TEMPLATE = app
TARGET = Changed
INCLUDEPATH += .

# Input
SOURCES += main.cpp
