######################################################################
# Automatically generated by qmake (3.0) Mon Jan 21 17:01:44 2019
######################################################################
QT += gui core widgets network
TEMPLATE = app
TARGET = HttpClient
INCLUDEPATH += .

# Input
HEADERS += logindialog.h mainwindow.h \
    download.h
FORMS += logindialog.ui mainwindow.ui
SOURCES += logindialog.cpp main.cpp mainwindow.cpp \
    download.cpp
