######################################################################
# Automatically generated by qmake (3.0) Wed Jul 31 14:06:31 2019
######################################################################
QT += widgets
TEMPLATE = app
TARGET = Button
INCLUDEPATH += .

# Input
SOURCES += main.cpp
