######################################################################
# Automatically generated by qmake (3.0) Fri Aug 2 09:42:56 2019
######################################################################
QT += widgets
TEMPLATE = app
TARGET = Time
INCLUDEPATH += .

# Input
HEADERS += TimeDialog.h ui_TimeDialog.h
FORMS += TimeDialog.ui
SOURCES += main.cpp TimeDialog.cpp
