######################################################################
# Automatically generated by qmake (3.0) Wed Jul 31 16:23:24 2019
######################################################################
QT += widgets
TEMPLATE = app
TARGET = Parent
INCLUDEPATH += .

# Input
SOURCES += main.cpp
