######################################################################
# Automatically generated by qmake (3.0) Thu Aug 1 15:06:54 2019
######################################################################
QT += widgets
TEMPLATE = app
TARGET = Calculator
INCLUDEPATH += .

# Input
HEADERS += CalculatorDialog.h
SOURCES += CalculatorDialog.cpp main.cpp
