######################################################################
# Automatically generated by qmake (3.0) Wed Jul 31 17:28:28 2019
######################################################################
QT += widgets
TEMPLATE = app
TARGET = Close
INCLUDEPATH += .

# Input
SOURCES += main.cpp
