######################################################################
# Automatically generated by qmake (3.0) Fri Aug 2 11:41:49 2019
######################################################################
QT += widgets
TEMPLATE = app
TARGET = Login
INCLUDEPATH += .

# Input
HEADERS += LoginDialog.h ui_LoginDialog.h
FORMS += LoginDialog.ui
SOURCES += LoginDialog.cpp main.cpp
