######################################################################
# Automatically generated by qmake (3.0) Thu Aug 1 17:20:17 2019
######################################################################
QT += widgets
TEMPLATE = app
TARGET = Calculator2
INCLUDEPATH += .

# Input
HEADERS += CalculatorDialog.h ui_CalculatorDialog.h
FORMS += CalculatorDialog.ui
SOURCES += CalculatorDialog.cpp main.cpp
